<!-- Generated by ai2html v0.97.0 - 2019-12-13 19:06 -->
<!-- ai file: FEM Online season 3 cert.ai -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Document</title>
</head>
  <style media="screen,print">
        #g-FEM-Online-season-3-cert-box,
        #g-FEM-Online-season-3-cert-box .g-artboard {
            margin: 0 auto;
        }

        #g-FEM-Online-season-3-cert-box p {
            margin: 0;
        }

        #g-FEM-Online-season-3-cert-box .g-aiAbs {
            position: absolute;
        }

        #g-FEM-Online-season-3-cert-box .g-aiImg {
            position: absolute;
            top: 0;
            left: 0;
            right: 0;
            bottom: 0;
            display: block;
            width: 100% !important;
        }

        #g-FEM-Online-season-3-cert-box .g-aiSymbol {
            position: absolute;
            box-sizing: border-box;
        }

        #g-FEM-Online-season-3-cert-box .g-aiPointText p {
            white-space: nowrap;
        }

        #g-FEM-Online-season-3-cert-Artboard_227 {
            /* position: relative; */
            overflow: hidden;
        }

        #g-FEM-Online-season-3-cert-Artboard_227 p {
            font-weight: 700;
            line-height: 16px;
            filter: alpha(opacity=100);
            -ms-filter: progid: DXImageTransform.Microsoft.Alpha(Opacity=100);
            opacity: 1;
            letter-spacing: 0em;
            font-size: 12px;
            text-align: left;
            color: rgb(0, 0, 0);
            text-transform: none;
            padding-bottom: 0;
            padding-top: 0;
            mix-blend-mode: normal;
            font-style: normal;
            height: auto;
            position: static;
        }

        #g-FEM-Online-season-3-cert-Artboard_227 .g-pstyle0 {
            line-height: 29px;
            height: 29px;
            font-size: 30px;
            color: rgb(100, 96, 96)
        }

        #g-FEM-Online-season-3-cert-Artboard_227 .g-pstyle1 {
            font-weight: 700;
            line-height: 72px;
            height: 72px;
            font-size: 60px;
            color: rgb(93, 101, 117);
        }

        #g-FEM-Online-season-3-cert-Artboard_227 .g-pstyle2 {
            font-weight: 700;
            line-height: 72px;
            height: 72px;
            font-size: 60px;
            color: rgb(255, 143, 195);
        }

        #g-FEM-Online-season-3-cert-Artboard_227 .g-pstyle3 {
            font-weight: 600;
            /* line-height: 58px;
            height: 58px; */
            font-size: 60px;
        }

        #g-FEM-Online-season-3-cert-Artboard_227 .g-pstyle4 {
            text-align: center;
            font-size: 25px;
            line-height: 30px;
            color: rgb(100, 96, 96);
        }

        #g-FEM-Online-season-3-cert-Artboard_227 .g-pstyle5 {
            font-weight: 600;
            margin-bottom: 10px;
            font-style: italic;
            line-height: 14px;
            height: 14px;
            font-size: 25px;
            text-align: center;
            color: rgb(100, 96, 96);
        }
  </style>
</head>
<body>
  <div class="ai2html"
       id="g-FEM-Online-season-3-cert-box">
    <!-- Artboard: Artboard_227 -->
    <div class="g-artboard"
         data-aspect-ratio="1.379"
         data-min-width="0"
         id="g-FEM-Online-season-3-cert-Artboard_227"
         style="max-width: 768px;height: 100vh">
      <div style="padding: 0 0 72.5061% 0;"></div><img alt=""
           class="g-aiImg"
           id="g-FEM-Online-season-3-cert-Artboard_227-img"
           src="images/certificate/fam-cert.jpg">
      <div class="g-Layer_1 g-aiAbs g-aiPointText"
           id="g-ai0-1"
           style="top:25%;margin-top:-15.4px;left:46.1497%;width:244px;">
        {{--  <p class="g-pstyle0">Online Level {{ $level }}</p>  --}}
      </div>
      <div class="g-Layer_1 g-aiAbs g-aiPointText"
           id="g-ai0-2"
           style="top:40%;margin-top:-38.6px;left:22%;width:600px;">
        <p class="g-pstyle1">PARTICIPANT CERTIFICATE</p>
      </div>
      <div class="g-Layer_1 g-aiAbs g-aiPointText"
           id="g-ai0-3"
           style="top:40%;margin-top:-38.6px;left:21.7%;width:600px;">
        <p class="g-pstyle2">PARTICIPANT CERTIFICATE</p>
      </div>
      <div class="g-Layer_1 g-aiAbs g-aiPointText"
           id="g-ai0-4"
           style="top:80%;margin-top:-30px;left:50%; transform: translate(-50%);">
        {{--  <p class="g-pstyle3">{{ $name }}</p>  --}}
      </div>
      <div class="g-Layer_1 g-aiAbs"
           id="g-ai0-5"
           style="padding: 6px 6px 6px 7px;top:90%;left:52.7028%;margin-left:-46.4844%;width:92.9688%;">
        <p class="g-pstyle4">For participating in the FEMALE AND MORE 30 days self-esteem and leadership program for young</p>
        <p class="g-pstyle4">females across Africa</p>
        <p>&nbsp;</p>
      </div>
      <div class="g-Layer_1 g-aiAbs g-aiPointText"
           id="g-ai0-6"
           style="top:127%;margin-top:-22.3px;left:78.6534%;margin-left:-101px;width:202px;">
        <p class="g-pstyle5">Kingsley N.T. Bangwell</p>
        <p class="g-pstyle5">CEO/Executive Director,</p>
        <p class="g-pstyle5">Youngstars Dev. Initiative</p>
      </div>
      <div class="g-Layer_1 g-aiAbs g-aiPointText"
           id="g-ai0-7"
           style="top:142%;margin-top:-7.8px;left:51.288%;margin-left:-106px;width:212px;">
        {{--  <p class="g-pstyle5">This {{ $day }} day of {{ $month }}, {{ $year }}</p>  --}}
      </div>
    </div>
  </div><!-- End ai2html - 2019-12-13 19:06 -->
</body>
</html>

{{--  <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body style="background:blueviolet; padding:0; margin:0">
    <img src="/images/certificate/fam-cert.jpg" alt="" style="postion:relative; height:100%;">
    <div>{{ $name }}</div>
    <div>{{ $day }}/{{ $month }}/ {{ $year }}</div>
</body>
</html>  --}}
